// Verbatim UI copy. PM refusal rule: UX Writer copy is used verbatim, never
// paraphrased — change it in copy.md first, then mirror here. Sources:
//   - auth (signup/mfa/totp/errors/a11y): docs/bets/WLT-1/stories/WLT-6 + WLT-7
//   - accounts/consent/connect/disconnect: docs/bets/WLT-2/stories/WLT-9/copy.md

export const COPY = {
  signup: {
    title: "Create your account",
    emailLabel: "Email",
    passwordLabel: "Password",
    passwordHelper: "At least 12 characters. A short sentence works well.",
    cta: "Create account",
    ctaLoading: "Creating account…",
    signinLink: "Already have an account? Sign in",
  },
  mfaEnroll: {
    title: "Secure your account with a passkey",
    body: "A passkey uses your face, fingerprint, or device PIN — no codes to type. It keeps your financial data locked to devices you trust.",
    cta: "Create passkey",
    loading: "Waiting for your device…",
    cancelledTitle: "Passkey not created",
    cancelledBody:
      "The passkey prompt was closed before finishing. Your account needs a passkey to continue.",
    cancelledCta: "Try again",
    success: "Passkey created. Your account is protected.",
    signout: "Sign out",
  },
  mfaUnsupported: {
    title: "This browser doesn't support passkeys",
    body: "To keep your financial data safe, we require a passkey. Use a current version of Chrome, Safari, Edge, or Firefox on this or another device, then sign in again.",
  },
  signin: {
    title: "Sign in",
    cta: "Sign in",
    ctaLoading: "Signing in…",
    signupLink: "New here? Create an account",
  },
  mfaChallenge: {
    title: "Confirm it's you",
    body: "Use your passkey to finish signing in.",
    retry: "Try again",
  },
  signinSuccess: "Welcome back.",
  // ── WLT-7: authenticator-app (TOTP) backup factor ────────────────────────
  security: {
    title: "Security",
    subtitle: "How you sign in and protect your account.",
    passkeyLabel: "Passkey",
    passkeyStatus: "Added",
    totpLabel: "Authenticator app",
    totpEmptyStatus: "Not set up",
    totpEmptyCta: "Add authenticator app",
    totpEnrolledStatus: "Added",
    totpRemove: "Remove",
    cancel: "Cancel",
  },
  nudge: {
    title: "Add a backup way to sign in",
    body: "Right now your passkey is the only way in. Add an authenticator app so you're not locked out if you lose your device.",
    cta: "Add a backup",
    dismiss: "Not now",
  },
  totpEnroll: {
    title: "Add your authenticator app",
    body: "Scan this with an authenticator app like Google Authenticator, 1Password, or Authy, then enter the 6-digit code it shows.",
    manualKeyLabel: "Can't scan? Enter this key in your app",
    manualKeyCopy: "Copy key",
    codeLabel: "6-digit code",
    cta: "Verify and add",
    loading: "Preparing…",
    verifying: "Verifying…",
    success: "Authenticator app added. You now have a backup.",
  },
  totpChallenge: {
    title: "Enter your authenticator code",
    body: "Open your authenticator app and enter the current 6-digit code.",
    codeLabel: "6-digit code",
    cta: "Verify",
    verifying: "Verifying…",
    retry: "Try again",
    usePasskey: "Use your passkey instead",
  },
  signinFallback: {
    useAuthenticator: "Use your authenticator app instead",
    noBackupTitle: "Can't use your passkey?",
    noBackupBody:
      "This account doesn't have a backup set up yet. Contact support and we'll help you get back in.",
  },
  totpRemove: {
    confirmTitle: "Remove your authenticator app?",
    confirmBody:
      "You'll go back to using only your passkey. You can add an authenticator again anytime.",
    confirmCta: "Remove",
    lastFactor:
      "You can't remove your only backup while it's your sole protection. Add another way to sign in first.",
  },
  errors: {
    validationEmail: "Enter a valid email address, like name@example.com.",
    validationPassword: "Your password needs at least 12 characters.",
    invalidCredentials: "That email and password combination doesn't match our records. Try again.",
    emailConfirmationRequired: "Please confirm your email first — check your inbox for the link we sent.",
    rateLimited: "Too many attempts. Wait a minute, then try again.",
    network: "You appear to be offline. Check your connection and try again.",
    server: "Something went wrong on our side — your information is safe. Try again in a minute.",
    unknown:
      "That didn't work, and we're not sure why. Try again; if it keeps happening, contact support.",
    totpInvalidCode: "That code isn't right. Check your authenticator app and try again.",
    totpExpiredCode: "That code expired. Enter the current one from your app.",
    totpAlreadyEnrolled: "You already have an authenticator app set up.",
  },
  // Verbatim from docs/bets/WLT-2/stories/WLT-9/copy.md (account aggregation).
  accounts: {
    title: "Accounts",
    emptyTitle: "No accounts connected yet",
    emptyBody: "Connect a bank to see your real transactions and let the platform work for you.",
    emptyCta: "Connect your first account",
    addAnother: "Add another account",
    syncing: "Syncing your transactions…",
    connectedStatus: "Connected",
    syncingStatus: "Syncing",
    importingStatus: "Importing…", // historical pull in progress (WLT-10)
    importingNote: "Importing your history — this can take a minute. You can keep using the app; we'll keep loading in the background.",
    needsReauthStatus: "Needs sign-in", // connection-health states surface fully in a later story
    errorStatus: "Error",
    rowLastSynced: "Updated {time}", // {time} = relative time (e.g. "just now", "2m ago")
    disconnect: "Disconnect",
  },
  consent: {
    title: "Connect your bank",
    body: "We use Plaid to securely connect your bank — we never see or store your bank login.",
    accessHeading: "What we'll access",
    accessItem1: "Your account names and balances",
    accessItem2: "Your transactions from the last 90 days",
    whyHeading: "Why",
    whyBody: "To show your real money picture and power your workflows and insights.",
    retentionHeading: "How long",
    retentionBody: "Until you disconnect. You can remove an account anytime, and we'll stop updating it.",
    cta: "Connect account",
    notNow: "Not now",
  },
  connect: {
    preparing: "Opening your bank…",
    success: "Account connected — importing your last 90 days of transactions.",
  },
  disconnectConfirm: {
    title: "Disconnect this account?",
    body: "We'll stop updating it and keep your existing history. You can reconnect anytime.",
    cta: "Disconnect",
    cancel: "Cancel",
  },
  aggregationErrors: {
    cancelled: "No account connected — try again when you're ready.",
    institutionUnavailable: "Your bank is temporarily unavailable — try again in a few minutes.",
    network: "Connection lost — check your internet and try again.",
    server: "Something went wrong on our side — your information is safe. Try again in a minute.",
  },
  a11y: {
    passwordShow: "Show password",
    passwordHide: "Hide password",
    capslock: "Caps Lock is on",
    codeHint: "Enter the 6 digits from your authenticator app.",
    copyKeyDone: "Key copied",
    intentGroup: "{cluster} — choose one", // {cluster} = the cluster header
    intentDeclared: "Saved. Putting your plan together.",
    // WLT-20 — the app shell nav
    openNav: "Open navigation menu",
    closeNav: "Close navigation menu",
    accountMenu: "Your account",
  },
  // WLT-11 intent front door (the cluster headers + starter-intent labels live in
  // @wealth/core INTENT_CLUSTERS — they're the taxonomy contract). Screen copy:
  intent: {
    title: "What would you like help with?",
    subtitle: "Pick what feels closest. You can always change it later.",
    cta: "Continue",
    explore: "I'm not sure yet — just let me look around",
    declaring: "Saving…",
    doneTitle: "Got it. We're putting your plan together.",
    doneBody: "We'll use this to set up the right things for you. Next, connect an account so we can work with your real numbers.",
    doneCta: "Connect an account",
    doneSecondary: "I'll do that later",
  },
  intentErrors: {
    save: "We couldn't save that — give it another try.",
    network: "You appear to be offline. Check your connection and try again.",
    server: "Something went wrong on our side — your information is safe. Try again in a minute.",
  },
  // WLT-12 workflow engine — net-worth snapshot card (copy.md verbatim).
  workflow: {
    planReadyTitle: "Your plan's ready",
    planReadyBody: "Connect an account and we'll turn this into your real money picture — and your first move.",
    planReadyConnectCta: "Connect an account",
    planReadyLater: "I'll do this later",
    assembling: "Putting your snapshot together…",
    snapshotTitle: "Your money, right now",
    netWorthLabel: "Net worth",
    assetsLabel: "Assets",
    debtsLabel: "Debts",
    action: "Set your target",
    targetTitle: "Set your target",
    targetSuggestion: "A good first target: {amount}",
    targetSuggestionAccept: "Use this target",
    targetOwnCta: "Choose my own",
    targetOwnLabel: "Your target",
    targetSave: "Set target",
    targetCancel: "Cancel",
    targetSaving: "Setting your target…",
    runningTitle: "You're set",
    runningBody: "We're tracking your money toward {amount}. You'll see how you're doing here.",
    runningCardStatus: "Running — tracking toward {amount}",
  },
  workflowErrors: {
    network: "Connection lost — check your internet and try again.",
    save: "Couldn't set that just now — try again.",
    server: "Something went wrong on our side — your information is safe. Try again in a minute.",
  },
  workflowA11y: {
    netWorth: "Net worth {netWorth}; assets {assets}, debts {debts}",
    targetSet: "Target set. We're putting your tracking together.",
  },
  // WLT-13 — the internal instrument panel (operator voice; copy.md verbatim).
  metrics: {
    title: "Metrics — internal",
    generatedAt: "Generated {timestamp}",
    preLaunchBanner: "Too little traffic to read as signal yet (total n = {n}). Baselines only — no KR verdicts.",
    ttfvHeading: "TTFV — signup → first action",
    ttfvP80Label: "p80",
    ttfvTargetHit: "✓ under 3m target",
    ttfvTargetMiss: "✗ above 3m target",
    ttfvSplitsHeading: "Split medians",
    ttfvSplitConnected: "→ connected",
    ttfvSplitPlan: "→ plan",
    ttfvSplitAction: "→ action",
    wawuHeading: "WAWU — weekly active wealth-building users",
    wawuWeekOf: "Week of {date}",
    returnHeading: "Return — weekly recap viewers (Day-7 return)",
    anomalyHeading: "Anomalies — detected / surfaced / acted / dismissed (precision watch)",
    funnelHeading: "Funnel — per-stage users + conversion",
    funnelColStage: "Stage",
    funnelColUsers: "Users",
    funnelColConv: "Conv %",
    funnelStageSignup: "Signed up",
    funnelStageMfa: "MFA enrolled",
    funnelStageConnected: "Account connected",
    funnelStageIntent: "Intent declared",
    funnelStagePlan: "Plan assembled",
    funnelStageAction: "First action",
    funnelIntentFootnote:
      "* Intent is declared before connecting (intent-first) — stages aren't a strict prerequisite chain.",
    nLabel: "n={n}",
    empty: "No events yet.",
    error: "Couldn't load metrics. Check the server logs.",
  },
  // WLT-14 — forgot password (self-serve reset). copy.md verbatim.
  forgot: {
    link: "Forgot password?",
    title: "Reset your password",
    body: "Enter your email and we'll send you a link to set a new password.",
    emailLabel: "Email",
    submit: "Send reset link",
    sending: "Sending…",
    backToSignIn: "Back to sign in",
    sentTitle: "Check your email",
    sentBody:
      "If an account exists for that email, we've sent a link to reset your password. It expires in a little while, so use it soon. Don't see it? Check your spam folder.",
  },
  reset: {
    title: "Set a new password",
    body: "Choose a new password for your account.",
    passwordLabel: "New password",
    submit: "Set new password",
    saving: "Saving…",
    doneTitle: "Your password's updated",
    doneBody:
      "You can sign in with your new password now. You'll still use your passkey to finish signing in — that hasn't changed.",
    doneCta: "Go to sign in",
    expiredTitle: "This link's expired",
    expiredBody:
      "Reset links can only be used once, and they don't last long. Request a new one and we'll send it over.",
    expiredCta: "Request a new link",
    // SUP-7 — accounts with an authenticator must prove the second factor before
    // a reset (a reset must not bypass MFA). Revealed when the server asks for it.
    mfaPrompt: "For your security, enter your authenticator code to finish resetting your password.",
    codeInvalid: "That code didn't match — enter the current one from your app.",
    codeExpired: "That code expired — enter the current one from your app.",
  },
  passwordErrors: {
    weak: "Your password needs at least 12 characters.",
    network: "You appear to be offline. Check your connection and try again.",
    server: "Something went wrong on our side — your information is safe. Try again in a minute.",
    rateLimited: "Too many attempts. Wait a minute, then try again.",
    samePassword: "That's already your password — choose a new one.",
  },
  resetA11y: {
    requested: "If an account exists, a reset link is on its way.",
    passwordUpdated: "Password updated. Taking you to sign in.",
  },
  // WLT-16 — the "since last time" recap. docs/bets/WLT-15/stories/WLT-16/copy.md verbatim.
  recap: {
    heading: "Since last time",
    loading: "Pulling your latest numbers…",
    coldStart: "We've started watching your money. You'll see how it's moving here in a few days.",
    movementUp: "Up {amount} since last week",
    movementDown: "Down {amount} since last week",
    movementFlat: "About the same as last week",
    netWorthLine: "Net worth {netWorth}",
    progressLabel: "Toward your target",
    progressValue: "{current} of {target}",
    progressPercent: "{percent}% there",
    onTrack: "You're on track.",
    behind: "A bit behind your target — here's a move.",
    actionAdjust: "Adjust your target",
    actionRaise: "Aim higher?",
    targetSuggestion: "A good target: {amount}",
    targetSuggestionAccept: "Use this target",
    targetOwnCta: "Choose my own",
    targetOwnLabel: "Your target",
    targetSave: "Save target",
    targetCancel: "Cancel",
    actionSaving: "Saving…",
    ackedLine: "Got it — we'll keep tracking.",
  },
  recapErrors: {
    network: "Connection lost — check your internet and try again.",
    save: "Couldn't save that just now — try again.",
    server: "Something went wrong on our side — your information is safe. Try again in a minute.",
  },
  recapA11y: {
    recap: "{movement}. Net worth {netWorth}. {percent}% toward your {target} target.",
    progressBar: "Progress toward target: {percent} percent",
    acked: "Saved. We'll keep tracking toward your target.",
    spend: "Where your money went: spent {total} this week, {comparison}. Top categories: {categories}.",
  },
  // WLT-17 — "where your money went" (spending vs last week). copy.md verbatim.
  recapSpend: {
    heading: "Where your money went",
    thisWeek: "Spent {total} this week",
    less: "{amount} less than last week",
    more: "{amount} more than last week",
    same: "About the same as last week",
    noComparison: "We'll compare this to last week once there's a bit more history.",
    topLabel: "Top",
  },
  // WLT-18 — anomalies ("worth a look"). copy.md verbatim. Plain, never alarming.
  anomaly: {
    heading: "Worth a look",
    largeCharge: "A larger-than-usual charge: {amount} in {category} on {date}.",
    recurring: "A bill looks due soon: about {amount} for {category}.",
    lowBalance: "One of your accounts is running low: {amount}.",
    reviewCta: "Review it",
    dismissCta: "Dismiss",
    reviewing: "Saving…",
    acked: "Thanks — noted.",
    dismissed: "Dismissed.",
  },
  anomalyErrors: {
    network: "Connection lost — check your internet and try again.",
    save: "Couldn't save that just now — try again.",
    server: "Something went wrong on our side — your information is safe. Try again in a minute.",
  },
  anomalyA11y: {
    callout: "Worth a look: {summary}",
    acked: "Noted. We'll keep an eye out.",
  },
  // WLT-20 — the app shell. docs/bets/WLT-19/stories/WLT-20/copy.md verbatim.
  shell: {
    brand: "Wealth at Your Fingertips",
    navLabel: "Main",
    skipToContent: "Skip to content",
  },
  nav: {
    dashboard: "Dashboard",
    budget: "Budget & Spending",
    goals: "Goals",
    debt: "Debt payoff",
    investments: "Investments",
    subscriptions: "Subscriptions",
    accounts: "Accounts",
  },
  account: {
    security: "Security",
    signOut: "Sign out",
  },
  comingSoon: {
    badge: "Coming soon",
    budget: "See where your money goes and set limits that fit your life.",
    goals: "Set targets for what matters and watch your progress add up.",
    debt: "A clear plan to pay down what you owe, faster.",
    investments: "See all your investments in one place, without the spreadsheet.",
    subscriptions: "Spot every recurring charge and cancel the ones you don't use.",
  },
  // WLT-21-1 — Budget & Spending. docs/bets/WLT-21/stories/WLT-21-1/copy.md verbatim.
  budget: {
    title: "Budget & Spending",
    subtitle: "Set a monthly limit per category and see how this month is tracking.",
    colCategory: "Category",
    colRecommended: "Recommended",
    colActual: "This month so far",
    colBudget: "Your budget",
    useThis: "Use this",
    coldStartDash: "—",
    coldStartNote: "We need about a month of history to suggest a number.",
    toggleAmount: "$",
    togglePercent: "%",
    amountLabel: "Monthly limit",
    amountPlaceholder: "0.00",
    percentLabel: "Percent of your typical monthly spending",
    percentHelper: "{percent}% of your typical monthly spending ≈ {amount}/mo",
    percentNeedsHistory: "Set a dollar amount for now — we'll have a percent once we've seen about a month.",
    setCta: "Set budget",
    saveCta: "Save",
    savingCta: "Saving…",
    editCta: "Edit",
    clearCta: "Clear",
    savedToast: "Budget saved.",
    clearedToast: "Budget cleared.",
    left: "{amount} left",
    over: "{amount} over",
    noBudget: "No budget set",
    addCta: "+ Add a category",
    pickerTitle: "Add a category to budget",
    pickerHint: "Pick a category to set a budget — even one you haven't spent in yet.",
    pickerEmpty: "You're already budgeting every category we see.",
    pickerCancel: "Cancel",
    emptyTitle: "Nothing to budget yet",
    emptyBody: "Connect an account and we'll show your spending by category so you can set budgets.",
    emptyCta: "Connect an account",
    otherCategory: "Other",
  },
  budgetErrors: {
    saveFailed: "We couldn't save that. Your entry is still here — try again.",
    invalidAmount: "Enter an amount greater than 0.",
    invalidPercent: "Enter a percent between 1 and 100.",
    network: "You appear to be offline. Check your connection and try again.",
  },
  budgetA11y: {
    table: "Your budgets by category",
    budgetInput: "Monthly budget for {category}",
    budgetTypeToggle: "Budget as a dollar amount or a percent",
    statusOver: "Over budget by {amount}",
    statusUnder: "{amount} left this month",
    addCategory: "Add a category to budget",
    saveStatus: "Budget saving status",
  },
  // WLT-21-2 — the year-spread view. docs/bets/WLT-21/stories/WLT-21-2/copy.md verbatim.
  budgetYear: {
    viewYear: "View the year",
    hideYear: "Hide",
    caption: "Monthly {category} spend — last 12 months",
    soFar: "so far",
    maxLabel: "Most: {amount}",
    capLegend: "Your budget: {amount}/mo",
    noHistory: "Not enough history yet to show the year.",
  },
  budgetYearA11y: {
    toggle: "Show the last 12 months of {category} spend",
    toggleCollapse: "Hide the last 12 months of {category} spend",
    seriesCaption: "{category} — monthly spend, last 12 months",
    monthAmount: "{month}: {amount}",
    currentMonth: "{month} (this month so far): {amount}",
  },
  // WLT-22-1 — drill into a category's line items. docs/bets/WLT-22/stories/WLT-22-1/copy.md verbatim.
  budgetDrill: {
    panelHeading: "What's in {category} this month",
    totalLabel: "Total",
    loading: "Loading your transactions…",
    empty: "No transactions in {category} this month.",
    error: "We couldn't load these just now — try again.",
    retry: "Try again",
  },
  budgetDrillA11y: {
    openItems: "Show the transactions in {category} this month ({amount})",
    closeItems: "Hide the transactions in {category} this month",
    list: "Transactions in {category} this month",
    itemLabel: "{date}, {merchant}, {amount}",
    colDate: "Date",
    colMerchant: "Merchant",
    colAmount: "Amount",
  },
} as const;
